name: Run Telegram Bot

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run Telegram bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }} # Truyền token từ GitHub Secrets vào biến môi trường
      run: node bot.js
